name: EPG Update

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
           node-version: 18

    - name: npm grab epg
      run: |
          npm install
          # npm run grab -- --channels=sites/sports/in.channels.xml --days=7 --maxConnections=10 --gzip --output=guides/sports/in.xml
          # npm run grab -- --site=tvguide.com --maxConnections=10 --output=guides/tvguide.com.xml
          npm run grab -- --site=tvpassport.com --maxConnections=10 --output=guides/tvpassport.com.xml
          # npm run grab -- --site=tvtv.us --maxConnections=10 --output=guides/tvtv.us.xml
    - name: Commit changes
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "Your Name"
        git add -f guides/tvpassport.com.xml
        git commit -m "Update xml"
        git push
