name: Channel Update

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
           node-version: 18

    - name: npm grab epg
      run: |
          npm install
          # npm run channels:parse -- --config=./sites/tvguide.com/tvguide.com.config.js --output=./sites/tvguide.com/tvguide.com.channels.xml
          npm run channels:parse -- --config=./sites/tvpassport.com/tvpassport.com.config.js --output=./sites/tvpassport.com/tvpassport.com.channels.xml
    - name: Commit changes
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "Your Name"
        # git add -f sites/tvguide.com/tvguide.com.channels.xml
        git add -f sites/tvpassport.com/tvpassport.com.channels.xml
        git commit -a -m "Channel update"
        git push
