name: TataPlay EPG update

on:
  schedule:
    - cron: '0 */8 * * *' # Daily schedule
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
           node-version: 18
      
    - name: npm grab epg
      run: |
          npm install
          npm run grab -- --site=watch.tataplay.com --output=tp.guide.xml
          
    - name: Commit changes
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "Your Name"
        git add tp.guide.xml
        git commit -m "Update tp.guide.xml"
        git push
